services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=1
      - VITE_HOST=0.0.0.0
    command: npm run compose:dev

  # Optionnel (Linux seulement): lance Electron dans le conteneur avec X11
  # Utilisez: docker compose -f docker-compose.dev.yml --profile linux-gui up electron-linux
  electron-linux:
    profiles: ["linux-gui"]
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - dev
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - ELECTRON_DISABLE_SECURITY_WARNINGS=true
    security_opt:
      - seccomp:unconfined
    ipc: host
    cap_add:
      - SYS_ADMIN
    # Attend Vite + le build main Electron, puis lance Electron sans sandbox
    command: sh -lc 'npx wait-on tcp:5173 dist-electron/main.js && npx electron --no-sandbox dist-electron/main.js'

volumes:
  node_modules:

